//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.718.0 using the following command:
// xscgen -n |common.xsd=EKAER.Schema.Common -n |ekaermanagement.xsd=EKAER.Schema.Management common.xsd ekaermanagement.xsd
namespace EKAER.Schema.Common
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UnloadReporterType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum UnloadReporterType
    {
        
        /// <summary>
        /// <para>A bejelentő jelentheti csak be a lerakodást!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentő jelentheti csak be a lerakodást!")]
        S,
        
        /// <summary>
        /// <para>A bejelentő és a címzett (Destination adatoknál megadott fél) is lejelentheti a lerakodást!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentő és a címzett (Destination adatoknál megadott fél) is lejelentheti a l" +
            "erakodást!")]
        D,
    }
    
    /// <summary>
    /// <para>Trade card státuszai. A státuszoknak sorrendisége van, meg van határozva hogy melyik státuszból melyikbe lehet csak lépni!</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Trade card státuszai. A státuszoknak sorrendisége van, meg van határozva hogy mel" +
        "yik státuszból melyikbe lehet csak lépni!")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TradeCardStatusType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeCardStatusType
    {
        
        /// <summary>
        /// <para>Prepare. Létrehozás után kerül ebbe a státuszba, amikor még csak tervezi a fuvart az ügyfél. Ebből a státuszból S-be lehet állítani!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Prepare. Létrehozás után kerül ebbe a státuszba, amikor még csak tervezi a fuvart" +
            " az ügyfél. Ebből a státuszból S-be lehet állítani!")]
        P,
        
        /// <summary>
        /// <para>Start, On route, under delivery, it is on it's way. Amikor felpakolták a járművet és elindult, úton van! Abből a státuszból F-be lehet váltani.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Start, On route, under delivery, it is on it\'s way. Amikor felpakolták a járművet" +
            " és elindult, úton van! Abből a státuszból F-be lehet váltani.")]
        S,
        
        /// <summary>
        /// <para>Finalized, unloaded. Amikor megérkezett a kirakodási helyre és lepakolták a szállítmányt. Ez a végső státusz itt van vége az életciklusnak. Ebből a státuszból nem lehet másik státuszba állítani.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Finalized, unloaded. Amikor megérkezett a kirakodási helyre és lepakolták a száll" +
            "ítmányt. Ez a végső státusz itt van vége az életciklusnak. Ebből a státuszból ne" +
            "m lehet másik státuszba állítani.")]
        F,
        
        /// <summary>
        /// <para>Inactive. Amikor nem véglegesedik megadott időn belül.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Inactive. Amikor nem véglegesedik megadott időn belül.")]
        I,
        
        /// <summary>
        /// <para>Deleted. Törölt státusz, csak P-ből kerülhet ide. Más státuszokból az I-be léphet csak!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Deleted. Törölt státusz, csak P-ből kerülhet ide. Más státuszokból az I-be léphet" +
            " csak!")]
        D,
    }
    
    /// <summary>
    /// <para>E: Export, I: Import, D:Domestic. A fuvar jellegét mutatja</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("E: Export, I: Import, D:Domestic. A fuvar jellegét mutatja")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TradeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeType
    {
        
        /// <summary>
        /// <para>Export</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Export")]
        E,
        
        /// <summary>
        /// <para>Domestic</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Domestic")]
        D,
        
        /// <summary>
        /// <para>Import</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Import")]
        I,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TradeReasonType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeReasonType
    {
        
        /// <summary>
        /// <para>Termék értékesítés / beszerzés</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Termék értékesítés / beszerzés")]
        S,
        
        /// <summary>
        /// <para>Saját tulajdonú termék - Törvény változás miatt kivezetve.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Saját tulajdonú termék - Törvény változás miatt kivezetve.")]
        A,
        
        /// <summary>
        /// <para>Bérmunka</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Bérmunka")]
        W,
        
        /// <summary>
        /// <para>Egyéb</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Egyéb")]
        O,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TradeCardType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlRootAttribute("TradeCardType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum TradeCardType
    {
        
        /// <summary>
        /// <para>Simple, egyszerüsített bevallás</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Simple, egyszerüsített bevallás")]
        S,
        
        /// <summary>
        /// <para>Normal, Normál adattartalmú bevallás</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Normal, Normál adattartalmú bevallás")]
        N,
    }
    
    /// <summary>
    /// <para>Eseményt rögzítő társrendszer</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Eseményt rögzítő társrendszer")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VrsEventOwnerType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum VrsEventOwnerType
    {
        
        /// <summary>
        /// <para>Fővárosi kamera</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Fővárosi kamera")]
        IKSZR,
        
        /// <summary>
        /// <para>Országos kamerarendszer</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Országos kamerarendszer")]
        VRS,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RecordStateType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum RecordStateType
    {
        
        /// <summary>
        /// <para>O: Original rekord, még nem lett módosítva</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("O: Original rekord, még nem lett módosítva")]
        O,
        
        /// <summary>
        /// <para>M: Midified, már lett módosítva a rekord, van előélete</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("M: Midified, már lett módosítva a rekord, van előélete")]
        M,
        
        /// <summary>
        /// <para>D: Deleted. Logikailag törölve lett!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("D: Deleted. Logikailag törölve lett!")]
        D,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FunctionCodeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlRootAttribute("FunctionCodeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum FunctionCodeType
    {
        
        /// <summary>
        /// <para>OK</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("OK")]
        OK,
        
        /// <summary>
        /// <para>Warning</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Warning")]
        WARNING,
        
        /// <summary>
        /// <para>Error</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Error")]
        ERROR,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReasonCodeType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public enum ReasonCodeType
    {
        
        /// <summary>
        /// <para>Sikeres!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sikeres!")]
        SUCCESS,
        
        /// <summary>
        /// <para>Általános / nem lekezelt -pl. technikai jellegű- hiba a feldolgozás során!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Általános / nem lekezelt -pl. technikai jellegű- hiba a feldolgozás során!")]
        OPERATION_FAILED,
        
        /// <summary>
        /// <para>Érvénytelen adatok a kérésben!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Érvénytelen adatok a kérésben!")]
        INVALID_INPUT,
        
        /// <summary>
        /// <para>Kérés nem értelmezhető, érvénytelen request!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kérés nem értelmezhető, érvénytelen request!")]
        INVALID_REQUEST,
        
        /// <summary>
        /// <para>Kérés fejléc nem értelmezhető, érvénytelen request header!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Kérés fejléc nem értelmezhető, érvénytelen request header!")]
        INVALID_REQUEST_HEADERS,
        
        /// <summary>
        /// <para>A kért csomag verzió még nem létezik!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kért csomag verzió még nem létezik!")]
        UNKNOWN_PACKAGE_VERSION,
        
        /// <summary>
        /// <para>A megadott azonosítóhoz nem tartozik érvényesített szállítmányozói regisztráció!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A megadott azonosítóhoz nem tartozik érvényesített szállítmányozói regisztráció!")]
        CARRIER_NOT_FOUND,
        
        /// <summary>
        /// <para>Bejelentésenként/menetlevelenként legalább egy tétel megadása kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Bejelentésenként/menetlevelenként legalább egy tétel megadása kötelező!")]
        TC_ITEM_NOT_FOUND,
        
        /// <summary>
        /// <para>Létrehozás esetén a tradeCard –on belül a tcn element-et el kell hagyni!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Létrehozás esetén a tradeCard –on belül a tcn element-et el kell hagyni!")]
        TC_CREATE_ELEMENT_FOUND,
        
        /// <summary>
        /// <para>carrier, carrierText: vagy az egyiket vagy a másikat kell magadni!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("carrier, carrierText: vagy az egyiket vagy a másikat kell magadni!")]
        TC_BOTH_CARRIER_FOUND,
        
        /// <summary>
        /// <para>A tradeCardItem element-en belül az id attribute-umot el kell hagyni!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A tradeCardItem element-en belül az id attribute-umot el kell hagyni!")]
        TCI_ID_FOUND,
        
        /// <summary>
        /// <para>sellerName: A fuvar irányától függetlenül, minden esetben kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerName: A fuvar irányától függetlenül, minden esetben kötelező!")]
        TC_SELLER_NAME_EMPTY,
        
        /// <summary>
        /// <para>sellerVatNumber: A fuvar irányától függetlenül, minden esetben kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerVatNumber: A fuvar irányától függetlenül, minden esetben kötelező!")]
        TC_SELLER_VAT_NUMBER_EMPTY,
        
        /// <summary>
        /// <para>sellerVatNumber: Hibás adószám!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerVatNumber: Hibás adószám!")]
        TC_SELLER_VAT_NUMBER_ERROR,
        
        /// <summary>
        /// <para>sellerVatNumber: Hibás adószám! Csak v1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerVatNumber: Hibás adószám! Csak v1.10 verziótól van használva!")]
        TC_SELLER_VAT_NUMBER_CDV_ERROR,
        
        /// <summary>
        /// <para>Országkód eltérés! Csak v1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Országkód eltérés! Csak v1.10 verziótól van használva!")]
        TC_FOREIGN_VAT_NUMBER_COUNTRY_CODE_MISMATCH,
        
        /// <summary>
        /// <para>sellerCountry: tradeType E és D esetén kötelező</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerCountry: tradeType E és D esetén kötelező")]
        TC_SELLER_COUNTRY_EMPTY,
        
        /// <summary>
        /// <para>sellerAddress: tradeType E és D esetén kötelező</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerAddress: tradeType E és D esetén kötelező")]
        TC_SELLER_ADDRESS_EMPTY,
        
        /// <summary>
        /// <para>destinationName: A fuvar irányától függetlenül, minden esetben kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationName: A fuvar irányától függetlenül, minden esetben kötelező!")]
        TC_DESTINATION_NAME_EMPTY,
        
        /// <summary>
        /// <para>destinationVatNumber: A fuvar irányától függetlenül, minden esetben kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationVatNumber: A fuvar irányától függetlenül, minden esetben kötelező!")]
        TC_DESTINATION_VAT_NUMBER_EMPTY,
        
        /// <summary>
        /// <para>destinationVatNumber: Hibás adószám!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationVatNumber: Hibás adószám!")]
        TC_DESTINATION_VAT_NUMBER_ERROR,
        
        /// <summary>
        /// <para>destinationVatNumber: Hibás adószám! Csak v1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationVatNumber: Hibás adószám! Csak v1.10 verziótól van használva!")]
        TC_DESTINATION_VAT_NUMBER_CDV_ERROR,
        
        /// <summary>
        /// <para>destinationCountrye: tradeType I esetén kötelező</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationCountrye: tradeType I esetén kötelező")]
        TC_DESTINATION_COUNTRY_EMPTY,
        
        /// <summary>
        /// <para>destinationAddress: tradeType I esetén kötelező</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationAddress: tradeType I esetén kötelező")]
        TC_DESTINATION_ADDRESS_EMPTY,
        
        /// <summary>
        /// <para>A fuvar irányától függetlenül, minden esetben kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A fuvar irányától függetlenül, minden esetben kötelező!")]
        TC_LOAD_LOCATION_NOT_FOUND,
        
        /// <summary>
        /// <para>loadLocation: tradeType I esetén nem lehet 'HU'</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("loadLocation: tradeType I esetén nem lehet \'HU\'")]
        TC_LOAD_LOCATION_CANT_BE_HUNGARY,
        
        /// <summary>
        /// <para>A fuvar irányától függetlenül, minden esetben kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A fuvar irányától függetlenül, minden esetben kötelező!")]
        TC_UNLOAD_LOCATION_NOT_FOUND,
        
        /// <summary>
        /// <para>unloadLocation: tradeType E esetén nem lehet 'HU'</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("unloadLocation: tradeType E esetén nem lehet \'HU\'")]
        TC_UNLOAD_LOCATION_CANT_BE_HUNGARY,
        
        /// <summary>
        /// <para>vehicle: tradeType E és D esetén kötelező</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("vehicle: tradeType E és D esetén kötelező")]
        TC_VEHICLE_NOT_FOUND,
        
        /// <summary>
        /// <para>Magyar címnek kell lennie!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Magyar címnek kell lennie!")]
        TC_LOCATION_NOT_HUNGARY,
        
        /// <summary>
        /// <para>A címadatoknál a name, vatNumber, country, zipCode, city, street mezők kötelezőek!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A címadatoknál a name, vatNumber, country, zipCode, city, street mezők kötelezőek" +
            "!")]
        TC_LOCATION_NOT_COMPLETE,
        
        /// <summary>
        /// <para>A törlés csak akkor hajtható végre, ha még “aktív” a bejelentés!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A törlés csak akkor hajtható végre, ha még “aktív” a bejelentés!")]
        TC_DELETE_ONLY_ACTIVE,
        
        /// <summary>
        /// <para>vehicle/plateNumber: A bejelentés véglegesítése előtt ki kell tölteni</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("vehicle/plateNumber: A bejelentés véglegesítése előtt ki kell tölteni")]
        TC_FINALIZE_VEHICLE_DATA_EMPTY,
        
        /// <summary>
        /// <para>arrivalDate: A bejelentés véglegesítése előtt ki kell tölteni</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("arrivalDate: A bejelentés véglegesítése előtt ki kell tölteni")]
        TC_FINALIZE_ARRIVAL_DATE_EMPTY,
        
        /// <summary>
        /// <para>A szállító nem módosíthatja a bejelentést!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A szállító nem módosíthatja a bejelentést!")]
        TC_MODIFY_BY_CARRIER_DISABLED,
        
        /// <summary>
        /// <para>addrNumber: veszélyes tétel esetén kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("addrNumber: veszélyes tétel esetén kötelező!")]
        TCI_DANG_PROD_ADRNUMBER_NOT_FOUND,
        
        /// <summary>
        /// <para>trasportLicense: veszélyes tétel esetén kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("trasportLicense: veszélyes tétel esetén kötelező!")]
        TCI_DANG_PROD_TRANSLIC_NOT_FOUND,
        
        /// <summary>
        /// <para>destinationCountry: tradeType I esetén csak 'HU' lehet</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationCountry: tradeType I esetén csak \'HU\' lehet")]
        TC_DESTINATION_MUST_BE_HUNGARY,
        
        /// <summary>
        /// <para>destinationCountry: tradeType E esetén nem lehet 'HU'</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationCountry: tradeType E esetén nem lehet \'HU\'")]
        TC_DESTINATION_CANT_BE_HUNGARY,
        
        /// <summary>
        /// <para>sellerCountry: tradeType E esetén csak 'HU' lehet</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerCountry: tradeType E esetén csak \'HU\' lehet")]
        TC_SELLER_MUST_BE_HUNGARY,
        
        /// <summary>
        /// <para>sellerCountry: tradeType I esetén nem lehet 'HU'</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("sellerCountry: tradeType I esetén nem lehet \'HU\'")]
        TC_SELLER_CANT_BE_HUNGARY,
        
        /// <summary>
        /// <para>Érvénytelen belépési adatok!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Érvénytelen belépési adatok!")]
        INVALID_USER_OR_PASSWORD,
        
        /// <summary>
        /// <para>A hívónak nincs joga a művelet végrehajtásához!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A hívónak nincs joga a művelet végrehajtásához!")]
        ACCESS_DENIED,
        
        /// <summary>
        /// <para>Az adófizető adatai nem találhatóak!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az adófizető adatai nem találhatóak!")]
        NO_TAX_DATA,
        
        /// <summary>
        /// <para>A felhasználó adófizetői adatai nem érvényesek!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A felhasználó adófizetői adatai nem érvényesek!")]
        USER_TAX_DATA_NOT_VALID,
        
        /// <summary>
        /// <para>destinationCountry: tradeType E esetén csak 'HU' lehet</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("destinationCountry: tradeType E esetén csak \'HU\' lehet")]
        TC_VTSZ_TOO_SHORT,
        
        /// <summary>
        /// <para>VTSZ nem ismert, érvénytelen!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("VTSZ nem ismert, érvénytelen!")]
        TC_VTSZ_UNKNOWN,
        
        /// <summary>
        /// <para>NÉBIH felír szám szükséges az áru bejelentéséhez!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("NÉBIH felír szám szükséges az áru bejelentéséhez!")]
        TC_FELIR_NEBIH_REG_NEEDED,
        
        /// <summary>
        /// <para>Nébih által engedélyezett első betárolási helynek nem felel meg a cím:</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nébih által engedélyezett első betárolási helynek nem felel meg a cím:")]
        TC_UNLOAD_ADDR_MUST_BE_REG_IN_NEBIH,
        
        /// <summary>
        /// <para>Érvénytelen felrakodási időpont!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Érvénytelen felrakodási időpont!")]
        TC_INVALID_LOADDATE,
        
        /// <summary>
        /// <para>Érvénytelen érkezési időpont!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Érvénytelen érkezési időpont!")]
        TC_INVALID_ARRIVALDATE,
        
        /// <summary>
        /// <para>Az érvényességi idő túl lett lépve!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az érvényességi idő túl lett lépve!")]
        TC_VALIDITY_EXCEEDED,
        
        /// <summary>
        /// <para>A rendszám megadása kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A rendszám megadása kötelező!")]
        TC_PLATENUMBER_MISSING,
        
        /// <summary>
        /// <para>A rendszám vagy felségjel nincs megadva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A rendszám vagy felségjel nincs megadva!")]
        TC_PLATENUMBER_COUNTRY_MISSING,
        
        /// <summary>
        /// <para>Jövőbeli érkezési időpont nem megengedett!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Jövőbeli érkezési időpont nem megengedett!")]
        TC_FUTURE_ARRIVAL_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Az érkezési időpont kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az érkezési időpont kötelező!")]
        TC_ARRIVALDATE_MISSING,
        
        /// <summary>
        /// <para>A berakodási időpont kötelező!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A berakodási időpont kötelező!")]
        TC_LOADDATE_MISSING,
        
        /// <summary>
        /// <para>A fuvar okok a tételnél a fuvar irányultságtól függően meghatározottak lehetnek csak!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A fuvar okok a tételnél a fuvar irányultságtól függően meghatározottak lehetnek c" +
            "sak!")]
        INVALID_REASON_WITH_TRADE_TYPE,
        
        /// <summary>
        /// <para>A hívónak nincs joga a feltöltés végrehajtásához!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A hívónak nincs joga a feltöltés végrehajtásához!")]
        TC_UPLOAD_ACCESS_DENIED,
        
        /// <summary>
        /// <para>A kérésben szereplő indexek egymáshoz képést nem egyediek!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kérésben szereplő indexek egymáshoz képést nem egyediek!")]
        TC_OP_INDEX_NOT_UNIQUE,
        
        /// <summary>
        /// <para>A módosítás törölt, inaktív vagy véglegesített státuszban nem engedélyezett!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A módosítás törölt, inaktív vagy véglegesített státuszban nem engedélyezett!")]
        TC_MODIFICATION_DISABLED,
        
        /// <summary>
        /// <para>A rendszám módosítására nincsen joga</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A rendszám módosítására nincsen joga")]
        TC_PLATE_NUMBER_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Az árumegérkezés lejelentéséhez nincsen joga</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árumegérkezés lejelentéséhez nincsen joga")]
        TC_UNLOAD_REPORT_NOT_ALLOWED,
        
        /// <summary>
        /// <para>A bejelentő nem engedélyezte a bejelentés kezelését!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentő nem engedélyezte a bejelentés kezelését!")]
        CARRIER_NOT_ASSIGNED,
        
        /// <summary>
        /// <para>Az árutétel tömegének módosításához nincs joga!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árutétel tömegének módosításához nincs joga!")]
        TCI_WEIGHT_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Az árutétel értékének módosításához nincs joga!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árutétel értékének módosításához nincs joga!")]
        TCI_VALUE_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Hibás adószám! Csak v1.6 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Hibás adószám! Csak v1.6 verziótól van használva!")]
        INVALID_VATNUMBER,
        
        /// <summary>
        /// <para>Hibás adóazonosító! Csak v1.6 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Hibás adóazonosító! Csak v1.6 verziótól van használva!")]
        INVALID_TAXIDENTICATIONNUMBER,
        
        /// <summary>
        /// <para>A termék VTSZ-e és a termék név nem módosítható! Csak v1.6 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A termék VTSZ-e és a termék név nem módosítható! Csak v1.6 verziótól van használv" +
            "a!")]
        TCI_MODIFY_PRODUCT_DISABLED,
        
        /// <summary>
        /// <para>Felrakodási adószám helytelen! Csak v1.6 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Felrakodási adószám helytelen! Csak v1.6 verziótól van használva!")]
        TC_LOAD_VAT_NUMBER_ERROR,
        
        /// <summary>
        /// <para>Lerakodási adószám helytelen! Csak v1.6 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Lerakodási adószám helytelen! Csak v1.6 verziótól van használva!")]
        TC_UNLOAD_VAT_NUMBER_ERROR,
        
        /// <summary>
        /// <para>Az árutétel értéke hiányzik! Csak v1.6 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árutétel értéke hiányzik! Csak v1.6 verziótól van használva!")]
        TCI_VALUE_MISSING,
        
        /// <summary>
        /// <para>A módosítás okának megadása kötelező! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A módosítás okának megadása kötelező! Csak v1.7 verziótól van használva!")]
        TC_MOD_REASON_MISSING,
        
        /// <summary>
        /// <para>A módosítás okának megadása kötelező! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A módosítás okának megadása kötelező! Csak v1.7 verziótól van használva!")]
        TCI_MOD_REASON_MISSING,
        
        /// <summary>
        /// <para>A tradeType értéke csak 'D' lehet! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A tradeType értéke csak \'D\' lehet! Csak v1.7 verziótól van használva!")]
        TC_ONLY_SELLER_DELIVERY_ALLOWED_WITH_TRADETYPE,
        
        /// <summary>
        /// <para>A sellerVatNumber nem egyezik az adott customer rögzített adószámával! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A sellerVatNumber nem egyezik az adott customer rögzített adószámával! Csak v1.7 " +
            "verziótól van használva!")]
        TC_SELLER_VATNUMBER_MUST_BE_CUSTOMERS,
        
        /// <summary>
        /// <para>A destinationVatNumber nem egyezik az adott customer rögzített adószámával! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A destinationVatNumber nem egyezik az adott customer rögzített adószámával! Csak " +
            "v1.7 verziótól van használva!")]
        TC_DESTINATION_VATNUMBER_MUST_BE_CUSTOMERS,
        
        /// <summary>
        /// <para>A kockázatos termék nem engedélyezett! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kockázatos termék nem engedélyezett! Csak v1.7 verziótól van használva!")]
        TCI_RISKY_TRADECARD_ITEM_ONLY_ALLOWED_WITH_SELLER_DELIVERY,
        
        /// <summary>
        /// <para>A isSellerDelivery módosítás nem engedélyezett! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A isSellerDelivery módosítás nem engedélyezett! Csak v1.7 verziótól van használva" +
            "!")]
        TC_SELLER_DELIVERY_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Véglegesítés nem engedélyezett! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Véglegesítés nem engedélyezett! Csak v1.7 verziótól van használva!")]
        TC_FINALIZE_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Cégadatok hianyosak! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Cégadatok hianyosak! Csak v1.7 verziótól van használva!")]
        TC_UNLOAD_LOCATION_COMPANY_INFO_MISSING,
        
        /// <summary>
        /// <para>A 'címzett azonos-e a kirakodás címzetjével' nyilatkozat kötelező! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A \'címzett azonos-e a kirakodás címzetjével\' nyilatkozat kötelező! Csak v1.7 verz" +
            "iótól van használva!")]
        TC_IS_DESTINATION_COMPANY_IDENTICAL_MISSING,
        
        /// <summary>
        /// <para>A 'címzett azonos-e a kirakodás címzetjével' nyilatkozat vagy kirakodás cégadatok kötelezőek! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A \'címzett azonos-e a kirakodás címzetjével\' nyilatkozat vagy kirakodás cégadatok" +
            " kötelezőek! Csak v1.7 verziótól van használva!")]
        TC_IS_DESTINATION_COMPANY_REQUIRED,
        
        /// <summary>
        /// <para>Nem engedélyezett adatmódostás! Csak v1.7 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nem engedélyezett adatmódostás! Csak v1.7 verziótól van használva!")]
        TC_NOT_ALLOWED_DATA_MODIFICATION,
        
        /// <summary>
        /// <para>GPS koordináta nem adható meg, ha a tételek között kozkázatos szerepel! Csak v1.8 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("GPS koordináta nem adható meg, ha a tételek között kozkázatos szerepel! Csak v1.8" +
            " verziótól van használva!")]
        TC_GPS_DATA_NOT_ALLOWED_WITH_RISKY_ITEM,
        
        /// <summary>
        /// <para>Tranzakció sátusza alapján nem végrehajtható a kérés! Csak v1.8 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tranzakció sátusza alapján nem végrehajtható a kérés! Csak v1.8 verziótól van has" +
            "ználva!")]
        INVALID_TRANSACTION_STATE,
        
        /// <summary>
        /// <para>A bejelentéshez nem található menetlevél! Csak v1.8 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentéshez nem található menetlevél! Csak v1.8 verziótól van használva!")]
        TC_DELIVERY_PLAN_MISSING,
        
        /// <summary>
        /// <para>A tétel módosítás okának megadása kötelező! Csak v1.8 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A tétel módosítás okának megadása kötelező! Csak v1.8 verziótól van használva!")]
        TCI_STATUS_MOD_REASON_MISSING,
        
        /// <summary>
        /// <para>A termék módosítás okának megadása kötelező! Csak v1.8 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A termék módosítás okának megadása kötelező! Csak v1.8 verziótól van használva!")]
        TCI_PRODUCT_MOD_REASON_MISSING,
        
        /// <summary>
        /// <para>Felségjel nem ismert, érvénytelen! Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Felségjel nem ismert, érvénytelen! Csak v1.9 verziótól van használva!")]
        TC_UNKNOWN_LICENCE_PLATE_COUNTRY_CODE,
        
        /// <summary>
        /// <para>A regisztrációhoz nem található érvényes elsődleges felhasználó, a belépés nem megengedett!  Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A regisztrációhoz nem található érvényes elsődleges felhasználó, a belépés nem me" +
            "gengedett! Csak v1.9 verziótól van használva!")]
        NO_VALID_MASTER_USER,
        
        /// <summary>
        /// <para>item-ben kötelező az operation-t küldeni! Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("item-ben kötelező az operation-t küldeni! Csak v1.9 verziótól van használva!")]
        TCI_ITEM_OPERATION_MISSING,
        
        /// <summary>
        /// <para>Az árutétel termék módosításához nincs joga! Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árutétel termék módosításához nincs joga! Csak v1.9 verziótól van használva!")]
        TCI_PRODUCT_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Az árutétel létrehozásához nincs joga! Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árutétel létrehozásához nincs joga! Csak v1.9 verziótól van használva!")]
        TCI_CREATE_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Az árutétel törléséhez nincs joga! Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Az árutétel törléséhez nincs joga! Csak v1.9 verziótól van használva!")]
        TCI_DELETE_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Fedezethiány! Csak v1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Fedezethiány! Csak v1.9 verziótól van használva!")]
        LOW_BALANCE,
        
        /// <summary>
        /// <para>A bejelentéshez inaktív vtsz-el rendelkező tétel tartozik! Csak 1.9 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentéshez inaktív vtsz-el rendelkező tétel tartozik! Csak 1.9 verziótól van" +
            " használva!")]
        TC_INACTIVE_CPA_FOUND,
        
        /// <summary>
        /// <para>A menetlevélhez tartozó lerakodási cím rossz! Csak 1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A menetlevélhez tartozó lerakodási cím rossz! Csak 1.10 verziótól van használva!")]
        TC_LOAD_LOCATION_ERROR,
        
        /// <summary>
        /// <para>A menetlevélhez tartozó fellerakodási cím rossz! Csak 1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A menetlevélhez tartozó fellerakodási cím rossz! Csak 1.10 verziótól van használv" +
            "a!")]
        TC_UNLOAD_LOCATION_ERROR,
        
        /// <summary>
        /// <para>A menetlevélhez tartozó lerakodási és felrakodási cím rossz! Csak 1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A menetlevélhez tartozó lerakodási és felrakodási cím rossz! Csak 1.10 verziótól " +
            "van használva!")]
        TC_LOAD_AND_UNLOAD_LOCATION_ERROR,
        
        /// <summary>
        /// <para>Nem megfelelő verzió! Csak 1.10 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nem megfelelő verzió! Csak 1.10 verziótól van használva!")]
        TC_REQUEST_VERSION_ERROR,
        
        /// <summary>
        /// <para>Adott TCN egy kérésben csak egyszer szerepelhet! Csak carrier 1.0 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Adott TCN egy kérésben csak egyszer szerepelhet! Csak carrier 1.0 verziótól van h" +
            "asználva!")]
        TC_TCN_NOT_UNIQUE,
        
        /// <summary>
        /// <para>A tétel beszerzési okának megadása kötelező tétel létrehozásakor! Csak carrier 1.0 verziótól van használva!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A tétel beszerzési okának megadása kötelező tétel létrehozásakor! Csak carrier 1." +
            "0 verziótól van használva!")]
        TCI_TRADE_REASON_MISSING,
        
        /// <summary>
        /// <para>Nem lehet hibernálni!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nem lehet hibernálni!")]
        TC_CUSTOMER_HIBERNATE_DENIED,
        
        /// <summary>
        /// <para>A Carrier törlés van!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A Carrier törlés van!")]
        TC_CARRIER_HIBERNATED,
        
        /// <summary>
        /// <para>Felrakodás dátuma nem definiált!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Felrakodás dátuma nem definiált!")]
        TC_LOADDATE_TIME_WARN,
        
        /// <summary>
        /// <para>A kirakodás időpontja csak a megérkezés bejelentésekor, az EKAER szám lezáráskor adható meg!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kirakodás időpontja csak a megérkezés bejelentésekor, az EKAER szám lezáráskor " +
            "adható meg!")]
        TC_ARRIVALDATE_TIME_ERROR,
        
        /// <summary>
        /// <para>Érvénytelen országkód!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Érvénytelen országkód!")]
        TC_INVALID_COUNTRY_CODE,
        
        /// <summary>
        /// <para>Érvénytelen országkód az adószámban!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Érvénytelen országkód az adószámban!")]
        TC_INVALID_VAT_NUMBER_COUNTRY_CODE,
        
        /// <summary>
        /// <para>A bejelentés a vonatkozó jogszabályok alapján nem módosítható!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentés a vonatkozó jogszabályok alapján nem módosítható!")]
        TC_FINALIZED_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>A bejelentés utólagos módosítása szállítmányozónak nem engedélyezett!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentés utólagos módosítása szállítmányozónak nem engedélyezett!")]
        TC_FINALIZED_CARRIER_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>Export bejelentések nem módosíthatóak lezárást követően!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Export bejelentések nem módosíthatóak lezárást követően!")]
        TC_FINALIZED_EXPORT_MOD_NOT_ALLOWED,
        
        /// <summary>
        /// <para>A bejelentés több alkalommal nem módosítható!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentés több alkalommal nem módosítható!")]
        TC_FINALIZED_NO_MORE_MOD_ATTEMPTS,
        
        /// <summary>
        /// <para>Csak a vonatkozó rendeletben meghatározott adatok módosíthatók!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Csak a vonatkozó rendeletben meghatározott adatok módosíthatók!")]
        TC_FINALIZED_MOD_INVALID_DATA_CHANGE,
        
        /// <summary>
        /// <para>A bejelentésben szereplő termékek nem törölhetők!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentésben szereplő termékek nem törölhetők!")]
        TC_FINALIZED_ITEM_DELETE_NOT_ALLOWED,
        
        /// <summary>
        /// <para>A bejelentéshez nem adható hozzá új termék!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A bejelentéshez nem adható hozzá új termék!")]
        TC_FINALIZED_ITEM_CREATE_NOT_ALLOWED,
        
        /// <summary>
        /// <para>A módosítás nem tartalmaz adatváltozást!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A módosítás nem tartalmaz adatváltozást!")]
        TC_FINALIZED_MOD_NO_DATA_CHANGE,
        
        /// <summary>
        /// <para>A Feladó/Címzett adószáma "HU" országkódot tartalmaz!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A Feladó/Címzett adószáma \"HU\" országkódot tartalmaz!")]
        TC_VAT_NUMBER_WARN,
        
        /// <summary>
        /// <para>A feladó és címzett adószáma megegyezik!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A feladó és címzett adószáma megegyezik!")]
        TC_VAT_NUMBER_ERROR,
        
        /// <summary>
        /// <para>A megadott VTSZ esetében nem nyilatkozhat az ÁFA kulcs miatti biztosíték mentességről!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A megadott VTSZ esetében nem nyilatkozhat az ÁFA kulcs miatti biztosíték mentessé" +
            "gről!")]
        TCI_INVALID_ASSURANCE_STATEMENT,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicHeaderType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BasicHeaderType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fault))]
    public partial class BasicHeaderType
    {
        
        /// <summary>
        /// <para>A kérés azonosítója, minden request-nél más</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kérés azonosítója, minden request-nél más")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("requestId")]
        public string RequestId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _version = "1.0";
        
        /// <summary>
        /// <para>A request verziószáma, a request struktúra verziója</para>
        /// <para xml:lang="en">Minimum length: 3.</para>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,2}\.[0-9]{1,3}.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1.0")]
        [System.ComponentModel.DescriptionAttribute("A request verziószáma, a request struktúra verziója")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(6)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,2}\\.[0-9]{1,3}")]
        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }
        
        /// <summary>
        /// <para>A kérés keletkezésének ideje</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kérés keletkezésének ideje")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("timestamp", DataType="dateTime")]
        public System.DateTime Timestamp { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BaseResultType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BaseResultType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class BaseResultType
    {
        
        /// <summary>
        /// <para>Sikeresség: OK, hiba ERROR, vagy WARNING</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Sikeresség: OK, hiba ERROR, vagy WARNING")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("funcCode")]
        public FunctionCodeType FuncCode { get; set; }
        
        /// <summary>
        /// <para>Végrehajtási eredmény kódja!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Végrehajtási eredmény kódja!")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reasonCode")]
        public ReasonCodeType ReasonCode { get; set; }
        
        /// <summary>
        /// <para>A végrehajtással kapcsolatos szöveges leírás ha szükséges. Általában akkor van töltve ha a funcCode nem SUCCESS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A végrehajtással kapcsolatos szöveges leírás ha szükséges. Általában akkor van tö" +
            "ltve ha a funcCode nem SUCCESS")]
        [System.Xml.Serialization.XmlElementAttribute("msg")]
        public string Msg { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicRequestType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BasicRequestType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BasicPackageQueryResponseType))]
    public partial class BasicRequestType : BasicHeaderType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicResponseType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BasicResponseType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fault))]
    public partial class BasicResponseType : BasicHeaderType
    {
        
        /// <summary>
        /// <para>Válasz sikeresség, eredmény adatok!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Válasz sikeresség, eredmény adatok!")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("result")]
        public BaseResultType Result { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicPackageQueryRequestType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicPackageQueryRequestType : BasicRequestType
    {
        
        /// <summary>
        /// <para>A lekérdezett csomag sorszáma</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A lekérdezett csomag sorszáma")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("packageNumber")]
        public decimal PackageNumber { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicPackageQueryResponseType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicPackageQueryResponseType : BasicRequestType
    {
        
        /// <summary>
        /// <para>A lekérdezett csomag sorszáma</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A lekérdezett csomag sorszáma")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("packageNumber")]
        public decimal PackageNumber { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("itemCount")]
        public decimal ItemCount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ItemCount property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemCountSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AuditDetailsType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuditDetailsType
    {
        
        /// <summary>
        /// <para>Módosítás időpontja</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Módosítás időpontja")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("modDate", DataType="dateTime")]
        public System.DateTime ModDate { get; set; }
        
        /// <summary>
        /// <para>Rekord állapota: A : active. I: Inactive</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Rekord állapota: A : active. I: Inactive")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("recordState")]
        public RecordStateType RecordState { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BasicJournaledRecordType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BasicJournaledRecordType
    {
        
        /// <summary>
        /// <para>A módosításkövetett rekord rekord audit mezői!</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A módosításkövetett rekord rekord audit mezői!")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("auditDetails")]
        public AuditDetailsType AuditDetails { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("id")]
        public string Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GPSCoordType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GPSCoordType
    {
        
        /// <summary>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 14.</para>
        /// <para xml:lang="en">Maximum exclusive value: 9999.99999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("latitude")]
        public decimal Latitude { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Total number of digits: 18.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 14.</para>
        /// <para xml:lang="en">Maximum exclusive value: 9999.99999999999999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("longitude")]
        public decimal Longitude { get; set; }
    }
    
    /// <summary>
    /// <para>Lezárt bejelentés módosításából eredő pótlékok lista típusa.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Lezárt bejelentés módosításából eredő pótlékok lista típusa.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AllowanceListType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AllowanceListType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class AllowanceListType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AllowanceType> _allowance;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("allowance")]
        public System.Collections.ObjectModel.Collection<AllowanceType> Allowance
        {
            get
            {
                return _allowance;
            }
            private set
            {
                _allowance = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AllowanceListType" /> class.</para>
        /// </summary>
        public AllowanceListType()
        {
            this._allowance = new System.Collections.ObjectModel.Collection<AllowanceType>();
        }
    }
    
    /// <summary>
    /// <para>Lezárt bejelentés módosításából eredő pótlékok típusa.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Lezárt bejelentés módosításából eredő pótlékok típusa.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AllowanceType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AllowanceType", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class AllowanceType
    {
        
        /// <summary>
        /// <para>A kiszabott pótlék összege</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kiszabott pótlék összege")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("allowanceValue")]
        public decimal AllowanceValue { get; set; }
        
        /// <summary>
        /// <para>A kiszabott pótlék esedékessége</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("A kiszabott pótlék esedékessége")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("allowanceDueDate", DataType="date")]
        public System.DateTime AllowanceDueDate { get; set; }
    }
    
    /// <summary>
    /// <para>Hiba esetén ilyen fault választ ada a server! result részen a hiba pontosabb definiálásával!</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Hiba esetén ilyen fault választ ada a server! result részen a hiba pontosabb defi" +
        "niálásával!")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.718.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fault", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("fault", Namespace="http://schemas.nav.gov.hu/EKAER/1.0/common")]
    public partial class Fault : BasicResponseType
    {
    }
}
